name: Dependency & Vulnerability Checks

on:
  schedule:
    - cron: '0 0 * * 1'  # every Monday at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  weekly-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trivy filesystem scan
        id: trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: .
          ignore-unfixed: true
          format: sarif
          output: trivy-results.sarif
          severity: HIGH,CRITICAL

      - name: Upload Trivy results to code scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      - name: Python dependency audit (pip-audit)
        id: pipaudit
        uses: pypa/gh-action-pip-audit@v1
        with:
          vulnerability-service: osv
          # Generate SARIF output for code scanning
          # sarif isn't yet GA in pip-audit action; fallback to logs parsing

      - name: Summarize scan results
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const title = 'Weekly Dependency & Vulnerability Report';
            const body = `Automated weekly scan completed.\n\n- Trivy: ${{ steps.trivy.outcome }}\n- pip-audit: ${{ steps.pipaudit.outcome }}\n\nPlease review security tab for details.`;
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
              labels: ['security','automation']
            });

